language: node_js
node_js:
  - "10.16.0"
sudo: true

dist: trusty # For sonar

addons:
  chrome: stable
  sonarcloud:
    organization: "rcronald"
    token:
      secure: "yu8GjwccEZpaOUV7c+I5a8sGb4pAPhmufY3sZmVbbieoFoPxjJ1gsbbDwuCMXtjXCC4MIH2YPMaqYfugVJeuLocwVWPQPNsBj0qVDPJbMTbQRqcK8TQt/Iz1H9RBQauWWGFl+UOftF7JvXydjkZGHYfUs5Br09Te58+8C01gsTpiXhmpxWKzr6FtAFDPP/7CEUI6Q3l7YHnzdj4TkiUTe6j4u+ZX1uMTGzt31HKOuhiEdy69NzUkqQHMKY+Dwjxm8byXlt+PwXu5TPfxhFAwy7RloBxVATj3MYh1HmVSzqWt68p2ouDqNtknZ1uc4dRSq3U2cWRFFfW2VOKiw/dmoM0DIaJV1x2vRZ0LSEI7PcDtkSbZEb0gW9M+2ZpYrn5LNnSYoSZU+nUQObG6LdSaFYVNnWxH7qMtARpNO75ZEo49XXfjj6wz/S5JpQ6EBouLbTMAqz0Xe0nkRr8jgwCiAIO5C27r8tCrLBGJyWOxeFddkk3epSAPIR2/iJtcbTOpTW4EZxsuAX2ntp70YWE18xK/VQ3OBfg54XMRDNltoW60HwN4UAfrSypBFRu4PLSPb3HIHq/Mc6PnOgmODj+77MkU4LlaQWyMEyRDb8ooL79IsgU7xsKTiDX6S6uYlloUybk13bdGQM/P1t0dH6R+ZuwoPs1K/G8EvZsRsEFF64k="

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

#script:
#  - yarn all_tests
#  - yarn build --prod --base-href $base_href #base_href should be given in travis as an environment variable

jobs:
  include:
    - stage: build
      script:
        - yarn lint
        - yarn build
        - sonar-scanner
    - stage: test
      script:
        - yarn test_headless
        - yarn e2e_headless
    - stage: prepare-deploy
      script:
        - yarn build --prod --base-href $base_href
      deploy:
        - provider: releases
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            tags: true
        - provider: pages
          skip_cleanup: true # To avoid cleanup of the artifact generated during script
          github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
          local_dir: dist/angular-travis-github-pages # Replace this with your project name
          on:
            branch: master
