language: node_js
node_js:
  - "10.16.0"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

#script:
#  - yarn all_tests
#  - yarn build --prod --base-href $base_href #base_href should be given in travis as an environment variable

jobs:
  include:
    - stage: build
      script:
        - yarn lint
        - yarn build
    - stage: test
      script:
        - yarn test_headless
        - yarn e2e_headless
    - stage: prepare-deploy
      script:
        - yarn build --prod --base-href $base_href
      deploy:
        - provider: releases
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          on:
            tags: true
        - provider: pages
          skip_cleanup: true # To avoid cleanup of the artifact generated during script
          github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
          local_dir: dist/angular-travis-github-pages # Replace this with your project name
          on:
            branch: master
